### PR TITLE
Improve causality detection for scripts

### PR DESCRIPTION
**Pull request by sohomdatta1**
- Add instances of `iframe.src` `iframe.srcdoc` `innerHTML`, `outerHTML` and inline loaded scripts

### CODE REVIEW

**Comment by sohomdatta1** [comment]
cc @ahsan238

**Comment by sohomdatta1** [comment]
@ahsan238 Can you test the latest version, iframe should be there

**Comment by sohomdatta1** [comment]
parentCardinality isn't really correct but I'm on it

**Comment by sohomdatta1** [comment]
cc @ahsan238

**Comment by ahsan238** [comment]
> cc @ahsan238

the root nodes of the test file (causality.html) seem to have been displaced again

**Comment by sohomdatta1** [comment]
> > cc @ahsan238
> 
> the root nodes of the test file (causality.html) seem to have been displaced again

Should be fixed right now :)

**Comment by sohomdatta1** [comment]
We still can't do much to resolve redirects `https://en.wikipedia.org` --> `https://en.wikipedia.org/wiki/Main_Page` so these will be considered different nodes

**Comment by ahsan238** [comment]
@sohomdatta1 , have you tested the post processor? There seems to be a runtime error when the main module tries to ingest the log.

**Comment by sohomdatta1** [comment]
Can you try the latest main branch ? The ingest failure should have been fixed :(

**Pull request merged**
